name: Conformance

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      RUBYOPT: -W0 # To suppress warnings

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true
    - uses: actions/setup-ruby@v1.0.0
      with:
        version: '2.6.x'
    - name: Install Fluentd
      run: |
        gem install -N fluentd
    - name: Install entr
      env:
        ENTR_VER: 4.4
      run: |
        curl -O http://eradman.com/entrproject/code/entr-${ENTR_VER}.tar.gz
        tar xf entr-${ENTR_VER}.tar.gz
        cd entr-${ENTR_VER}
        ./configure
        make test
        sudo make install
        cd $GITHUB_WORKSPACE
    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
    - name: Setup Python for testing
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.8.x'
    - name: Install cwltest
      run: pip install cwltest
    - name: Run example
      run: cwltest --tool $GITHUB_WORKSPACE/ep3-runner --test test.yml --timeout=30 --junit-xml=junit.xml
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: junit-example.xml
        path: junit.xml
    - name: Prepare CWL repository for conformance test
      run: git clone --depth 1 https://github.com/common-workflow-language/common-workflow-language.git cwl
    - name: Run conformance test
      run: |
        cd cwl
        ./run_test.sh RUNNER=$GITHUB_WORKSPACE/ep3-runner --badgedir=badges --junit-xml=junit.xml --timeout=30 || true
        cd $GITHUB_WORKSPACE
    - name: Save badges
      if: success() && github.event_name == 'push'
      run: |
        git clone --depth 1 https://${GITHUB_ACTOR}:${CONFORMANCE_TOKEN}@github.com/tom-tan/conformance.git

        cd conformance
        mkdir -p conformance/ep3/cwl_${cwlVersion}
        rm -rf conformance/ep3/cwl_${cwlVersion}/ep3_latest
        cp -r $GITHUB_WORKSPACE/cwl/${cwlVersion}/badges conformance/ep3/cwl_${cwlVersion}/ep3_latest
        commit=$(echo $GITHUB_SHA | cut -b -6)
        printf '{ "subject": "commit", "status": "%s", "color": "blue" }' $commit > conformance/ep3/cwl_${cwlVersion}/ep3_latest/commit.json

        git add conformance/ep3/cwl_${cwlVersion}/ep3_latest
        git config user.name "ep3 bot"
        git config user.email "ep3-bot@users.noreply.github.com"
        git diff-index --quiet HEAD || git commit -m "Conformance test of ep3 for CWL ${cwlVersion}" -m " Commit: ${GITHUB_SHA}"
        git push --quiet
      env:
        cwlVersion: v1.0
        CONFORMANCE_TOKEN: ${{ secrets.CONFORMANCE_TOKEN }}
    - uses: actions/upload-artifact@v1
      with:
        name: junit.xml
        path: cwl/v1.0/junit.xml
    - uses: mxschmitt/action-tmate@v1
      if: false
