name: Run conformance test

on: [push, pull_request]

jobs:

  build:

    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      RUBYOPT: -W0 # To suppress warnings

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        submodules: true
    - uses: actions/setup-ruby@v1.0.0
      with:
        version: '2.6.x'
    - name: Install Fluentd
      run: |
        gem install -N fluentd
    - name: Install entr and jq for Linux
      if: runner.os == "Linux"
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends entr jq
    - name: Install entr and jq for mac
      if: runner.os == "macOS"
      run: |
        brew install entr jq
    - uses: actions/setup-node@v1.1.0
    - name: Run example
      run: |
        $GITHUB_WORKSPACE/ep3-runner --debug examples/workflow.cwl examples/inputs.yml | jq .
    - name: Setup Python for testing
      uses: actions/setup-python@v1.1.1
    - name: Install cwltest
      run: |
        pip install cwltest
    - name: Prepare CWL repository for conformance test
      run: |
        git clone --depth 1 https://github.com/common-workflow-language/common-workflow-language.git cwl
    - name: Run conformance test
      run: |
        cd cwl
        ./run_test.sh RUNNER=$GITHUB_WORKSPACE/ep3-runner --badgedir=badges --timeout=30
